version: "3.8"
services:
  web:
    image: silverbars/spring-boot-to-docker:latest
    container_name: web
    volumes:
      - target/*.jar
    ports:
      - "8080:8080"
    networks:
      front_net:
        ipv4_address: 10.20.30.10
        aliases:
          - web
  web1:
    image: silverbars/spring-boot-to-docker:latest
    container_name: web_1
    volumes:
      - target/*.jar
    ports:
      - "8081:8080"
    networks:
      front_net:
        ipv4_address: 10.20.30.20
        aliases:
          - web_1

networks:
  front_net:
    ipam:
      driver: default
      config:
        - subnet: 10.20.30.0/24

volumes:
  db-data: